- name: Install the mosquitto broker
  apt:
    name: "{{ item }}"
  loop:
    - mosquitto
    - mosquitto-clients

- name: Copy the bridging configuration
  template:
    src: gir-bridge.conf.j2
    dest: /etc/mosquitto/conf.d/gir-bridge.conf
  notify: restart mosquitto
