- name: Set machine hostname
  hostname:
    name: "{{ ansible_hostname }}"

- name: Update package list
  apt:
    update_cache: yes
    cache_valid_time: 3600

#- name: Upgrade all packages to the latest version
#  apt:
#    name: "*"
#    state: latest

- name: Install common python packages
  apt:
    name: "{{ item }}"
  with_items:
    - git
    - python-pip
    - python-virtualenv

- name: Create Python virtualenv
  command: virtualenv pyenv -p python3
  args:
    creates:  "/home/{{ ansible_user }}/pyenv"
  become: no
