- name: "Setup group {{ledslie_group}}"
  group:
    name: "{{ledslie_group}}"
    system: yes

- name: "Setup user {{ledslie_user}}"
  user:
    name: "{{ledslie_user}}"
    group: "{{ledslie_group}}"
    groups:
      - dialout
    system: yes

- name: Installing systemd processor templates
  template:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
  with_items: "{{ledslie_processor}}"
  tags:
    - systemd

- name: Installing ledslie target
  template:
    src: "ledslie.target"
    dest: "/etc/systemd/system/ledslie.target"
  tags:
    - systemd

- name: Start ledslie processer services
  systemd:
    name: ledslie.target
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items: "{{ledslie_processor}}"
  tags:
    - update
    - systemd
