- name: Installing systemd content templates
  template:
    src: "ledslie-content.service-tmpl"
    dest: "/etc/systemd/system/ledslie-{{ item }}.service"
  with_items: "{{ledslie_content}}"

- name: Reload systemd config
  command: systemctl daemon-reload

- name: Start ledslie content services
  systemd:
    name: "ledslie-{{ item }}"
    state: restarted
    enabled: yes
  with_items: "{{ledslie_content}}"
  tags:
    - update
